### ISSUE TITLE
Cannot select any plans

### ISSUE THREAD

**Issue by dictav** [p0deje/vagrant-vultr#1]
https://github.com/p0deje/vagrant-vultr/blob/master/lib/vagrant-vultr/helpers/client.rb#L86

vps_plan_id method always returns 29.

**Comment by p0deje** [comment]
I've seen you fixed it in https://github.com/dictav/vagrant-vultr/commit/8c52e5727fc3b86513782793ef7a9c02ce5605a4. If you can send a pull request, I'll be happy to merge it.

**Comment by dictav** [comment]
I'm sorry. I was not able to pass all tests.
