### ISSUE TITLE
Unable to choose plan, because Vultr API sometimes returns two entries

### ISSUE THREAD

**Issue by pastcompute** [p0deje/vagrant-vultr#3]
Hi, I am unable to provision to "Sydney" region with plan "768 MB RAM,15 GB SSD,1.00 TB BW"

It seems after checking the JSON return that there are _two_ entries returned by vultr with that plan name:

From `wget https://api.vultr.com/v1/plans/list -O- | json_pp`:

```
   "31" : {
      "disk" : "15",
      "available_locations" : [
         19,
         25
      ],
      "windows" : false,
      "name" : "768 MB RAM,15 GB SSD,1.00 TB BW",
      "price_per_month" : "5.00",
      "bandwidth_gb" : "1024",
      "VPSPLANID" : "31",
      "plan_type" : "SSD",
      "bandwidth" : "1.00",
      "vcpu_count" : "1",
      "ram" : "768"
   },
```

and

```
   "29" : {
      "disk" : "15",
      "available_locations" : [
         1,
         2,
         3,
         4,
         5,
         6,
         7,
         8,
         9,
         12,
         24,
         39
      ],
      "windows" : false,
      "name" : "768 MB RAM,15 GB SSD,1.00 TB BW",
      "price_per_month" : "5.00",
      "bandwidth_gb" : "1024",
      "VPSPLANID" : "29",
      "plan_type" : "SSD",
      "bandwidth" : "1.00",
      "vcpu_count" : "1",
      "ram" : "768"
   },
```

I need plan 29 but Ruby is selecting from the other tuple

I'm guessing the solution would be to detect multiple entries in the function `vps_plan_id` and merge the results together, except I have no idea about how to go about that using Ruby.

Other alternative is to also let the vagrant file choose plan by number as well

**Comment by p0deje** [comment]
I'm not really maintaining this plugin, but pull requests with the fix are welcome (regardless of the option you prefer).

**Comment by pastcompute** [comment]
@p0deje I'm actively using this plugin again; am happy to become maintainer if you are looking still

**Comment by p0deje** [comment]
@pastcompute Great news!

I've invited you to become a collaborator on GitHub. I need your email address to give you release permissions to Rubygems.

**Comment by azohra** [comment]
@pastcompute - the reason for this is because there are actually 2 versions of all plans, even though they only show one version on the UI.

```hcl
VPSPLANID	NAME					VCPU	RAM	DISK	BANDWIDTH	PRICE
87		512 MB RAM,125 GB SATA,1.00 TB BW	1	512	125	1.00		5.00
201		1024 MB RAM,25 GB SSD,1.00 TB BW	1	1024	25	1.00		5.00
88		1024 MB RAM,250 GB SATA,2.00 TB BW	1	1024	250	2.00		10.00
202		2048 MB RAM,40 GB SSD,2.00 TB BW	1	2048	40	2.00		10.00
89		2048 MB RAM,500 GB SATA,3.00 TB BW	1	2048	500	3.00		20.00
203		4096 MB RAM,60 GB SSD,3.00 TB BW	2	4096	60	3.00		20.00
90		3072 MB RAM,750 GB SATA,4.00 TB BW	2	3072	750	4.00		30.00
91		4096 MB RAM,1000 GB SATA,5.00 TB BW	2	4096	1000	5.00		40.00
204		8192 MB RAM,100 GB SSD,4.00 TB BW	4	8192	100	4.00		40.00
115		8192 MB RAM,110 GB SSD,10.00 TB BW	2	8192	110	10.00		60.00
205		16384 MB RAM,200 GB SSD,5.00 TB BW	6	16384	200	5.00		80.00
116		16384 MB RAM,110 GB SSD,20.00 TB BW	4	16384	110	20.00		120.00
206		32768 MB RAM,300 GB SSD,6.00 TB BW	8	32768	300	6.00		160.00
117		24576 MB RAM,110 GB SSD,30.00 TB BW	6	24576	110	30.00		180.00
118		32768 MB RAM,110 GB SSD,40.00 TB BW	8	32768	110	40.00		240.00
207		65536 MB RAM,400 GB SSD,10.00 TB BW	16	65536	400	10.00		320.00
208		98304 MB RAM,800 GB SSD,15.00 TB BW	24	98304	800	15.00		640.00
```

I work on a fair amount of vultr projects as it pertains to terraform & ansible, so I am happy to answer any questions you might have. 

I would honestly advise thinking about a packer + terraform approach rather than a vagrant provider, however - its awesome someone is working on this!

**Comment by pastcompute** [comment]
@p0deje Please use bugs at andrew mcdonnell dot net for rubygems

I guess I can see if I can resolve that open PR

**Comment by p0deje** [comment]
Do you have an account on RubyGems? I cannot find one with such an email.

**Comment by pastcompute** [comment]
Sorry, things just got busy at work this week. Made the account now.

**Comment by p0deje** [comment]
@pastcompute Done! You now have full access. Have fun!

**Comment by Windol** [comment]
I would like to collaborate with this project to keep the Gem up to date on RubyGems.
I made a fix for this issue and already created the pull request #16. If any contributors are still active on this project, please do the merge and update in RubyGems. Otherwise, if you can give me the permissions, I'll do the update myself.

**Comment by p0deje** [comment]
@pastcompute Are you still active on the project?

**Comment by p0deje** [comment]
@Windol Are you willing to actively maintain the gem? There are few open issues that needs support.

**Comment by pastcompute** [comment]
Hi @p0deje  sorry, I havent checked in in a while, I dont even have a dev env set up for this at the moment. I''m happy to give access

**Comment by pastcompute** [comment]
I logged into rubygems, you are already an owner as well @p0deje - or do I need to do something

BTW I do actually use vultr from time to time, so I will try and keep a more active eye on things, but for the next couple of weeks I'm rather snowed under

**Comment by p0deje** [comment]
@pastcompute I do have access, just wondering if you could figure out @Windol PR and cut a new release, or shall we search for a new maintainer.

**Comment by Windol** [comment]
> @Windol Are you willing to actively maintain the gem? There are few open issues that needs support.

@p0deje I can help, however my knowledge of Ruby is just beginning and I would need help starting support for the new API version.

**Comment by p0deje** [comment]
@Windol OK, I've released a new version. Let me know if there is something else that needs to be merged.
