### ISSUE TITLE
vagrunt-vultr hits api rate limits

### ISSUE THREAD

**Issue by artemave** [p0deje/vagrant-vultr#7]
![image](https://cloud.githubusercontent.com/assets/23721/23875804/a7288316-0832-11e7-868a-3bbb828dabfb.png)

Weirdly enough, this doesn't happen locally, but always happens in travis.

**Comment by p0deje** [comment]
I no longer maintain this gem, but @mkaczanowski has agreed to be a maintainer, so I'll leave this to him.

**Comment by artemave** [comment]
For the time being, I published a temporary gem with the fix https://rubygems.org/gems/vagrant-vultr2

**Comment by p0deje** [comment]
@artemave Do you want to maintain this one? I can give you full access.

**Comment by artemave** [comment]
@p0deje I don't have enough time to be an official maintainer, sorry!
